COMMON_LANGUAGE_CODE_KEY = "language_code"
COMMON_SERIAL_NUMBER_KEY = "serial_number"
COMMON_PART_NUMBER_KEY = "part_number"
COMMON_PRODUCT_NAME_KEY = "product_name"
COMMON_FRU_FILE_ID = "fru_file_id"

# Chassis Info Area
CHASSIS_INFO_CHASSIS_TYPE_YAML_KEY = "chassis_type"
CHASSIS_INFO_PART_NUMBER_YAML_KEY = COMMON_PART_NUMBER_KEY
CHASSIS_INFO_SERIAL_NUMBER_YAML_KEY = COMMON_SERIAL_NUMBER_KEY
CHASSIS_INFO_CUSTOM_INFO_FIELDS_YAML_KEY = "custom_info_fields"

# Board Info Area
BOARD_INFO_LANGUAGE_CODE_KEY = COMMON_LANGUAGE_CODE_KEY
BOARD_INFO_MANUFACTURING_DATETIME_KEY = "manufacturing_datetime"
BOARD_INFO_MANUFACTURER_KEY = "manufacturer"
BOARD_INFO_PRODUCT_NAME_KEY = COMMON_PRODUCT_NAME_KEY
BOARD_INFO_SERIAL_NUMBER_KEY = COMMON_SERIAL_NUMBER_KEY
BOARD_INFO_PART_NUMBER_KEY = COMMON_PART_NUMBER_KEY
BOARD_INFO_FRU_FILE_ID_KEY = COMMON_FRU_FILE_ID
BOARD_INFO_CUSTOM_INFO_FIELDS_KEY = "custom_manufacturing_fields"

# Product Info Area
PRODUCT_INFO_LANGUAGE_CODE_KEY = COMMON_LANGUAGE_CODE_KEY
PRODUCT_INFO_MANUFACTURER_NAME_KEY = "manufacturer_name"
PRODUCT_INFO_PRODUCT_NAME_KEY = COMMON_PRODUCT_NAME_KEY
PRODUCT_INFO_PART_NUMBER_KEY = COMMON_PART_NUMBER_KEY
PRODUCT_INFO_PRODUCT_VERSION_KEY = "product_version"
PRODUCT_INFO_SERIAL_NUMBER_KEY = COMMON_SERIAL_NUMBER_KEY
PRODUCT_INFO_ASSET_TAG_KEY = "asset_tag"
PRODUCT_INFO_FRU_FILE_ID_KEY = COMMON_FRU_FILE_ID
PRODUCT_INFO_CUSTOM_INFO_FIELDS_KEY = "custom_info_fields"

# Management Access Record
MANAGEMENT_ACCESS_RECORD_SUB_TYPE_KEY = "type"
MANAGEMENT_ACCESS_RECORD_VALUE_KEY = "value"
