COMMON_LANGUAGE_CODE_KEY = "language_code"
COMMON_SERIAL_NUMBER_KEY = "serial_number"
COMMON_PART_NUMBER_KEY = "part_number"
COMMON_PRODUCT_NAME_KEY = "product_name"
COMMON_FRU_FILE_ID = "fru_file_id"

# Root
ROOT_AREAS_KEY = "areas"

# Length Type
LENGTH_TYPE_TYPE_KEY = "type"
LENGTH_TYPE_VALUE_KEY = "value"

# Areas
AREA_CHASSIS_INFO_KEY = "chassis_info_area"
AREA_BOARD_INFO_KEY = "board_info_area"
AREA_PRODUCT_INFO_KEY = "product_info_area"
AREA_MULTIRECORD_KEY = "multirecord_area"

# Chassis Info Area
CHASSIS_INFO_CHASSIS_TYPE_KEY = "chassis_type"
CHASSIS_INFO_PART_NUMBER_KEY = COMMON_PART_NUMBER_KEY
CHASSIS_INFO_SERIAL_NUMBER_KEY = COMMON_SERIAL_NUMBER_KEY
CHASSIS_INFO_CUSTOM_INFO_FIELDS_KEY = "custom_info_fields"

# Board Info Area
BOARD_INFO_LANGUAGE_CODE_KEY = COMMON_LANGUAGE_CODE_KEY
BOARD_INFO_MANUFACTURING_DATETIME_KEY = "manufacturing_datetime"
BOARD_INFO_MANUFACTURER_KEY = "manufacturer_name"
BOARD_INFO_PRODUCT_NAME_KEY = COMMON_PRODUCT_NAME_KEY
BOARD_INFO_SERIAL_NUMBER_KEY = COMMON_SERIAL_NUMBER_KEY
BOARD_INFO_PART_NUMBER_KEY = COMMON_PART_NUMBER_KEY
BOARD_INFO_FRU_FILE_ID_KEY = COMMON_FRU_FILE_ID
BOARD_INFO_CUSTOM_INFO_FIELDS_KEY = "custom_manufacturing_fields"

# Product Info Area
PRODUCT_INFO_LANGUAGE_CODE_KEY = COMMON_LANGUAGE_CODE_KEY
PRODUCT_INFO_MANUFACTURER_NAME_KEY = "manufacturer_name"
PRODUCT_INFO_PRODUCT_NAME_KEY = COMMON_PRODUCT_NAME_KEY
PRODUCT_INFO_PART_NUMBER_KEY = COMMON_PART_NUMBER_KEY
PRODUCT_INFO_PRODUCT_VERSION_KEY = "product_version"
PRODUCT_INFO_SERIAL_NUMBER_KEY = COMMON_SERIAL_NUMBER_KEY
PRODUCT_INFO_ASSET_TAG_KEY = "asset_tag"
PRODUCT_INFO_FRU_FILE_ID_KEY = COMMON_FRU_FILE_ID
PRODUCT_INFO_CUSTOM_INFO_FIELDS_KEY = "custom_info_fields"

# MultiRecord Area
MULTIRECORD_TYPE_KEY = "type"
MULTIRECORD_VALUE_KEY = "value"

# Management Access Record
MANAGEMENT_ACCESS_RECORD_SUB_TYPE_KEY = "sub_record_type"
MANAGEMENT_ACCESS_RECORD_VALUE_KEY = "value"
